### ISSUE TITLE
Doesn't work in Mac

### ISSUE THREAD

**Issue by alejeindrox** [clytras/react-native-fresco#2]
I am using your solution for the problem with fresco by react native and the image is not working yet it is pixelated, I followed all the steps you indicated. The problem I think is because of how the ndk is configured in mac, I downloaded the ndk directly from the link and I also tried doing it using Android Studio but when I use the ndk-build the following problem occurs:

> MacBook-Pro:~ us$ ndk-build
> Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
> Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: /Users/us/Library/Android/sdk/ndk/21.0.6113669/build/core/build-local.mk/jni/Android.mk    
> /Users/us/Library/Android/sdk/ndk/21.0.6113669/build/core/add-application.mk:88: *** Android NDK: Aborting...    .  Stop.

Do you know some way to solve it using mac?

These are my enviroment variables:

```
export ANDROID_HOME=~/Library/Android/sdk
export ANDROID_SDK_ROOT=~/Library/Android/sdk
export ANDROID_NDK=~/Library/Android/sdk/ndk/21.0.6113669
export NDK_PROJECT_PATH=~/Library/Android/sdk/ndk/21.0.6113669/build/core/build-local.mk
export ANDROID_AVD_HOME=~/.android/avd
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_NDK
```

**Comment by clytras** [comment]
I have tested it with MacOS Catalina and it worked on my MacMini.
Did you create `android/libraries/fresco/local.properties` with `ndk.dir` set to the correct NKD path?
Does the project compile successfully?
Do you see Fresco Image Pipeline binaries get generated while building the project?

**Comment by alejeindrox** [comment]
Yes in my 

`android/libraries/fresco/local.properties`

setup

```
ndk.dir=/Users/us/Library/Android/sdk/ndk/21.0.6113669
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
```

And compile the whole project without any problem.

I did not see any Fresco Image Pipeline binaries generated while building the project.

Would you need me to show you some other configuration file to see why it doesn't generate any Fresco Image Pipeline binaries?

**Comment by clytras** [comment]
I am away from my MacMini so I can't test it using Android Studio NDK, but that shouldn't be any of a problem.

It would be helpful if you can create a [pastebin](https://pastebin.com/) with **ALL** the compile output from `yarn android` to the end. Do a clean first `cd android && ./gradlew` clean" or create a new project using `npx`.

**Comment by alejeindrox** [comment]
Now Fresco Image Pipeline binaries are Building but the application now crash during the splash (when loading) has this happened before ??

This is what the console shows: https://pastebin.com/YCVBzX0D
And in case you need the Metro Bundler: https://pastebin.com/TNZUFQpM

This happens in a totally new clean project.

**Comment by clytras** [comment]
I can't see any binaries getting generated at building. Are you sure this is after a clear or a fresh `npx`? It looks like most of the Fresco lib does not compile. Take a look at a normal build with with all Fresco binaries get compile and generated https://pastebin.com/Ybr422BC

I'll leave this open until I can reach my MacMini to re-test it out.

**Comment by alejeindrox** [comment]
Here you are: https://pastebin.com/gX4WJyZv
Would you need anything else??

**Comment by clytras** [comment]
You said that the app crashes on start. Can you create a pastebin with the LOGCAT log when the app starts so to see the errors?

**Comment by alejeindrox** [comment]
Yes the app crashes on start.
Using `npx react-native log-android` : https://pastebin.com/0ExSzgp3
And `adb logcat *:S ReactNative:V ReactNativeJS:V` : https://pastebin.com/tmQUPUgh

**Comment by alejeindrox** [comment]
I fixed it by doing the following:

in package.json
`"fresco-clone": "git clone https://github.com/facebook/fresco.git android/libraries/fresco && cd android/libraries/fresco && git checkout tags/v2.1.0 && cd ../../..",`
for
`"fresco-clone": "git clone https://github.com/facebook/fresco.git android/libraries/fresco && cd android/libraries/fresco",`

And in android/build.gradle
`classpath('com.android.tools.build:gradle:3.4.1')`
for
`classpath('com.android.tools.build:gradle:3.5.3')`

And ready, it's a question of updates. It would be good to know what is the maximum capacity or the maximum weight or the maximum size that it accepts images because some doesn't take them, it doesn't give an error but it doesn't show them and I imagine it has to do with a limit that I don't know. Thank you

**Comment by clytras** [comment]
The `v2.1.0` fresco lib has to be checked out because that's the version that comes with `RN 0.61`, it's dangerous to compile directly from master.

As for gradle, I can't remember why I've had `3.4.1` but I remember there was a reason for that also.

I'll check it out on the mac again.
